### ISSUE TITLE
Simplification?

### ISSUE THREAD

**Issue by alixaxel** [Kikobeats/regex-word-boundary#5]
Stumbled across this and thought I should share an optimization in case you want to implement it:

```js
new RegExp(`\b(?:${collection.join('|')})\b`, flags);
```

It's using a non-capturing group to avoid specifying the word boundary tokens on every word.

Also, it would probably be wise to escape the words within `collection` for special characters:

```js
RegExp.escape = (value) => {
  return value.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
};

new RegExp(`\b(?:${collection.map(RegExp.escape).join('|')})\b`, flags);
```

**Comment by Kikobeats** [comment]
wow thanks for that!

about escape the regex is totally a thing I need to add there! I used [escape-string-regexp](https://www.npmjs.com/package/escape-string-regexp) in other modules and it's worth it 👍 

Do you want to do a PR with both things? 🙂
